runtime: python37

instance_class: F1
includes:
  - env_vars.yaml

# handlers:
#   - url: /api
#     secure: always
#     script: auto

#   - url: /.*
#     static_files: static/\1
#     upload: static/.*

beta_settings:
  cloud_sql_instances: jetuplno:europe-west3:postgres=tcp:5432

handlers:
  - url: /app
    static_files: static/index.html
    upload: static/index.html

  - url: /app/(.*)
    # static_dir: static
    static_files: static/\1
    upload: static/.*
    secure: always
    
  - url: /
    secure: always
    script: auto
