runtime: python37

instance_class: F1
includes:
  - env_vars.yaml

default_expiration: "1h"

handlers:
  - url: /api/.*
    secure: always
    script: auto

  - url: /
    secure: always
    static_files: static/index.html
    upload: static/index.html
    expiration: "15m"

  - url: /(.*)
    secure: always
    static_files: static/\1
    upload: static/.*
